name: the_rick_and_morty_api_with_cubit
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.6
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
